<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>ExileLens</AssemblyName><ApplicationIcon>Assets/ExileLens.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../ExileLens.Core/ExileLens.Core.csproj" /></ItemGroup>
<ItemGroup><Resource Include="Assets/ExileLens.ico" /></ItemGroup>
<ItemGroup>
  <PackageReference Include="Tesseract" Version="5.2.0" />
</ItemGroup><ItemGroup><Content Include="tessdata/eng.traineddata" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"/><Content Include="ThirdParty/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"/></ItemGroup></Project>
